/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./app/Vues/**/*.{php,js}",
    "./public/**/*.{js,css}",
    "./input.css",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0050cb",
        "primary-container": "#0066ff",
        "primary-fixed": "#dae1ff",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001849",
        "on-primary-fixed-variant": "#003fa4",
        secondary: "#495e8a",
        "secondary-container": "#b7ccfe",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#b1c6f9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#415681",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#314671",
        "primary-dark": "#003ea8",
        tertiary: "#006181",
        "tertiary-container": "#007ba3",
        "tertiary-fixed": "#c2e8ff",
        "tertiary-fixed-dim": "#75d1ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f3f9ff",
        "on-tertiary-fixed": "#001e2b",
        "on-tertiary-fixed-variant": "#004d67",
        background: "#f8f9ff",
        "background-light": "#f6f6f8",
        "background-dark": "#0b0e14",
        surface: "#f8f9ff",
        "surface-light": "#f8f9ff",
        "surface-dark": "#161b26",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "inverse-primary": "#b3c5ff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#424656",
        outline: "#727687",
        "outline-variant": "#c2c6d8",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        success: "#10b981",
        danger: "#dc2626",
        "red-accent": "#f87171",
        "emerald-accent": "#10b981",
        "emerald-custom": "#10b981",
        "text-dark": "#e0e0e0",
        "text-light": "#111827",
        "border-dark": "#282e39",
        "border-light": "#cbd5e1",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "label-mono": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        unit: "4px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
