export const APP_ROUTES = [
  { path: "/", title: "Accueil", layout: "auth", requireAuth: false },
  {
    path: "/documentation",
    title: "Documentation",
    layout: "auth",
    requireAuth: false,
  },
  { path: "/login", title: "Connexion", layout: "auth", requireAuth: false },
  { path: "/logout", title: "Déconnexion", layout: "auth", requireAuth: false },
  {
    path: "/get-started",
    title: "Inscription",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/company/register",
    title: "Inscription Entreprise",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/company/configuration",
    title: "Configuration Entreprise",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/company/activate",
    title: "Activation Entreprise",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/acount/activate",
    title: "Activation Compte",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/accept-invitation",
    title: "Accepter Invitation",
    layout: "auth",
    requireAuth: false,
  },
  { path: "/403", title: "Accès Refusé", layout: "auth", requireAuth: false },
  {
    path: "/404",
    title: "Page Non Trouvée",
    layout: "auth",
    requireAuth: false,
  },

  {
    path: "/app",
    title: "Application",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/dashboard",
    title: "Tableau de bord",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/documents",
    title: "Documents",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/documents/creer",
    title: "Créer Document",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/documents/:id/editer",
    title: "Éditer Document",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/inventaire",
    title: "Inventaire",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/mouvements",
    title: "Mouvements",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/articles",
    title: "Articles",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/versements",
    title: "Versements",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/folder",
    title: "Dossiers",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/importer",
    title: "Importer",
    layout: "dashboard",
    requireAuth: true,
  },
  { path: "/plans", title: "Plans", layout: "dashboard", requireAuth: true },
  {
    path: "/plans/creer",
    title: "Créer Plan",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/plans/:id/editer",
    title: "Éditer Plan",
    layout: "dashboard",
    requireAuth: true,
  },
  {
    path: "/welcome",
    title: "Bienvenue",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/workspace/setup",
    title: "Configuration Workspace",
    layout: "auth",
    requireAuth: false,
  },
  {
    path: "/company/team",
    title: "Équipe Entreprise",
    layout: "dashboard",
    requireAuth: true,
  },
  { path: "/test", title: "Test", layout: "dashboard", requireAuth: true },
  { path: "/tester", title: "Tester", layout: "dashboard", requireAuth: true },
];

export const SIDEBAR_ITEMS = [
  { label: "Documents", icon: "description", path: "/documents" },
  { label: "Inventaire", icon: "inventory", path: "/inventaire" },
  { label: "Mouvements", icon: "swap_horiz", path: "/mouvements" },
  { label: "Articles", icon: "inventory_2", path: "/articles" },
  { label: "Versements", icon: "payments", path: "/versements" },
  { label: "Plans", icon: "analytics", path: "/plans" },
  { label: "Import", icon: "upload_file", path: "/importer" },
  { label: "Team", icon: "group", path: "/company/team" },
  { label: "Setup", icon: "settings", path: "/workspace/setup" },
];
